### PR TITLE
Support operation BrowseNodeLookup

### PR DESCRIPTION
**Pull request by kauegimenes**

### CODE REVIEW

**Comment by kauegimenes** [comment]
I am not sure why Travis is returning this errors, i was able to test in my computer.

**Comment by masterT** [comment]
I don't know why, checks failed on my PR too #18. Maybe @t3chnoboy knows why.

**Comment by masterT** [comment]
I would be nice to update the README and maybe add an example in the `./examples` dir to show how to use the new feature.

**Comment by t3chnoboy** [comment]
@masterT @kauegimenes Build is green on master though... Looks like something wrong with travis config for PRs. Anyway, we need to update travis config. They've switched to containers recently.

**Comment by t3chnoboy** [comment]
lgtm, @kauegimenes can you please fix the indentation?

**Comment by kauegimenes** [comment]
@t3chnoboy @masterT I just included the example, updated the readme and i fixed the identation.

**Comment by masterT** [comment]
:+1: Nice!

**Comment by masterT** [comment]
@t3chnoboy ready for merge/bump version/publish? Do you want me to do it ?

**Comment by t3chnoboy** [comment]
Yep! Good to merge :+1:

**Pull request merged**
