### PR TITLE
Return Product API Errors from the Request

### PR DESCRIPTION
**Pull request by FdezRomero**
Hi there!

I was annoyed that I wasn't getting errors from the API as they are shown at the [Product API Scratchpad](http://associates-amazon.s3.amazonaws.com/scratchpad/index.html) and added a few lines so the module can return these and know exactly what happened (now you can only see there are no Items in the result).

So API errors inside the `Request` node like this one:

```xml
<Errors>
  <Error>
    <Code>AWS.ECommerceService.ItemNotAccessible</Code>
    <Message>This item is not accessible through the Product Advertising API.</Message>
  </Error>
</Errors>
```

Are being returned as errors in the callback/promise methods in JSON:

```javascript
[{
  "Error":
    [{
      "Code": ["AWS.ECommerceService.ItemNotAccessible"],
      "Message": ["This item is not accessible through the Product Advertising API."]
    }]
}]
```

Let me know if there's anything wrong with this or missing.

### CODE REVIEW

**Comment by masterT** [comment]
It looks good!

**Comment by FdezRomero** [comment]
Thanks for merging @masterT, the Travis CI test failed though.

**Comment by masterT** [comment]
Yep, I am looking to fix it now.

**Comment by masterT** [comment]
I looked up the [Amazon Error Docs](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ErrorMessages.html) and the `AWS.ECommerceService.ItemNotAccessible` is related to the method `ItemLookup`, so I will only check if there is an error when doing this method.

**Comment by masterT** [comment]
@FdezRomero are you sure you want to return the results as well, beside the error?

**Comment by FdezRomero** [comment]
Not sure about others methods really, but the `AWS.ECommerceService.ItemNotAccessible` was just an example. I've seen other errors when using `ItemLookup` and if Amazon had to return an error in other methods, this would be how they would return it, so I made it method-independent.

Regarding wether to return the results or not when using callbacks, I chose the conservative option of providing both and letting the developer choose what to do. From the docs, you should first check the existence of an error anyway. But it's true that the behaviour is different for promises, when you would just get the error in the `.catch()` and no results. So the choice is freedom vs. consistency, but I felt I was no one to make that decision ;-) I'm sure you can make a more informed decision.

**Comment by masterT** [comment]
All right! It makes sens!

**Comment by masterT** [comment]
This is an response when a make a request that throw an `AWS.ECommerceService.ItemNotAccessible`. There is no `Items.Item` in the response, so when using callback, it will pass only the error.

```js
{ '$': { xmlns: 'http://webservices.amazon.com/AWSECommerceService/2011-08-01' },
  OperationRequest:
   [ { RequestId: [Object],
       Arguments: [Object],
       RequestProcessingTime: [Object] } ],
  Items: [ { Request: [Object] } ] }
```

**Comment by FdezRomero** [comment]
If that is what the API returns, that's what a developer would expect, right? It's good to know anyway.

**Comment by masterT** [comment]
Exactly!

**Comment by masterT** [comment]
@FdezRomero I just publish the new version of the package!

**Comment by FdezRomero** [comment]
@masterT Thanks a lot! Hope to keep collaborating in the future.

**Pull request merged**
