### PR TITLE
Test isolation

### PR DESCRIPTION
**Pull request by masterT**
- Update dependencies
- Refactor the test

### CODE REVIEW

**Comment by masterT** [comment]
I invalidated my Amazon API credentials, don't worry.

**Comment by masterT** [comment]
I did not know how if it was a good idea to test the 'query' of the HTTPS request.

Also I think we should and handle an 500 internal server error.

What do you think?

**Comment by t3chnoboy** [comment]
> I did not know how if it was a good idea to test the 'query' of the HTTPS request.

why not?

>Also I think we should and handle an 500 internal server error.
yeah, better error handling would be nice, but I don't think it should be a part of this PR

**Comment by masterT** [comment]
Should we merge this now and enhance the test later? Or do it _now_ and then merge so we can insert PR #76?

**Comment by t3chnoboy** [comment]
@masterT 🚢!

**Pull request merged**
