### PR TITLE
Don't clobber global promise

### PR DESCRIPTION
**Pull request by sethsamuel**
There's an open thread in es6-promise (https://github.com/stefanpenner/es6-promise/issues/140) to fix this at the library level, but currently the global promise is being clobbered by the "polyfill" even without calling `polyfill`.

This quick fix avoids that problem.

### CODE REVIEW

**Comment by sethsamuel** [comment]
I ended up doing some additional refactoring while getting the tests to pass. Current test failures are due to the travis secret not decoding, I think.

If you'd prefer a more limited PR I can try to pull out just the promise fix.

**Comment by t3chnoboy** [comment]
Looks like something's wrong with my amazon credentials.
Do the tests pass locally?

**Comment by sethsamuel** [comment]
Travis secrets don't unlock on PRs (so the values don't leak to any PR requester). You can run the tests locally with the environment variables set to the AWS secrets and they should pass.

**Comment by t3chnoboy** [comment]
Awesome! Thank you @sethsamuel

**Pull request merged**
