### PR TITLE
cannot access TotalResults and TotalPages 

### PR DESCRIPTION
**Pull request by pgraemer**
i cannot access TotalResults or TotalPages because only the respObj.Items[0].Item is returned.

i would prefer getting the respObj.Items[0] instead of respObj.Items[0].Item.

to not brake older versions you could passing the whole respObj.Items[0] as a second argument to the callback.

### CODE REVIEW

**Comment by pgraemer** [comment]
i was not able to get the test running so the build may fail :(

**Comment by t3chnoboy** [comment]
Hey @pgraemer!
Looks good! All the tests passed locally, so this is good to merge.
Can you please update the documentation? Also adding at least one test would be very helpful, but not crucial. 
What was your problem with running the tests locally?

**Comment by pgraemer** [comment]
the test problem that has to be  be a problem on my system, ill check that tomorrow update docs + tests.

Awesome!

**Comment by t3chnoboy** [comment]
Danke schön :smile:

**Comment by pgraemer** [comment]
i updated docs & tests.

All the tests passed locally but travis still complains? i havent used travis so maybe u can help?

**Comment by t3chnoboy** [comment]
Sure, I'll take a look!

**Pull request merged**
