### PR TITLE
Support all params

### PR DESCRIPTION
**Pull request by masterT**
Support any params in the query, this way it is possible to fully use the [ItemLookup](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemLookup.html) and [ItemSearch](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html) methods.

See pull request #16

### CODE REVIEW

**Comment by masterT** [comment]
The tests are passing on my computer, I don't get it. 

```
$ npm test

> amazon-product-api@0.2.4 test /Users/simon/Documents/personal/progr_stuff/sources/amazon-product-api-forked
> mocha

child_process: customFds option is deprecated, use stdio instead.


  generateQueryString(query, method, credentials)
    ✓ should return a string

  createClient(credentials)
    ✓ should return amazon product api client with item search method

  client.itemSearch(query, cb)
    when credentials are valid
      when no callback is passed
        ✓ should return search results from amazon (456ms)
        ✓ should work with custom domain (706ms)
      when callback is passed
        ✓ should return search results from amazon (334ms)
    when credentials are invalid
      when no callback is passed
        ✓ should return an error (127ms)
      when callback is passed
        ✓ should return an error (136ms)

  query string
    ✓ should be a valid url
    ✓ should include a valid timestamp
    ✓ should include keywords
    ✓ should be signed


  11 passing (2s)
```

**Comment by t3chnoboy** [comment]
sweet!

**Comment by masterT** [comment]
Thanks! 
It looks like if the credentials were not set during the tests.

**Comment by t3chnoboy** [comment]
Looks very good! I can add you to the repo as a collaborator if you don't mind.

**Comment by masterT** [comment]
That would be great thanks.

**Comment by t3chnoboy** [comment]
Done! What's your npm username?

**Comment by masterT** [comment]
It's [mastert](https://www.npmjs.com/~mastert)!

**Comment by t3chnoboy** [comment]
:+1: 
Can you publish the latest version?
There are lots of changes. I think we should bump minor version. So it should be 0.3.0

**Comment by masterT** [comment]
Yeah that makes a sens!

**Pull request merged**
