### PR TITLE
Fix for BrowseNodeLookup support in the callback.

### PR DESCRIPTION
**Pull request by Codepoet77**
Fix to support BrowseNodeLookup in the callback. Other minor non functional changes that you will notice are formatting changes to make it consistent. Spaces before parens are fairly standard and pass JSHint as well.

### CODE REVIEW

**Comment by masterT** [comment]
Did the tests pass on your local machine? I think the credentials are not set correctly on  travis-ci when your are not on the branch master. 

It looks good, but I think we should do one of the options below:
1. put space *everywhere* before function's parenthesis
2. don't put space before function's parenthesis

What do you think @t3chnoboy @Codepoet77?

**Comment by Codepoet77** [comment]
@t3chnoboy @masterT
I am using Adobe Brackets and it doesn't even have the option to not have a space after a function. The auto beautify feature automatically does this. I'm pretty sure this is common place now. I also read up on it as well and it seems like it is a preference in many Stackoverflow articles.

Let me know what you guys think.

**Comment by masterT** [comment]
@Codepoet77 @t3chnoboy I don't really mind haha, but as I said, it should be everywhere or nowhere.

**Comment by Codepoet77** [comment]
Made the formatting change.

**Comment by masterT** [comment]
Good :+1: !

**Comment by masterT** [comment]
@Codepoet77 @t3chnoboy I just published the new version on npm.

**Comment by t3chnoboy** [comment]
Cool! thank you!

**Pull request merged**
