### PR TITLE
Added ItemLookup Method

### PR DESCRIPTION
**Pull request by JuanCrg90**
Hello again.

I added a method for get the item lookup of a product.

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemLookup.html
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/EX_LookupbyUPC.html

I hope you can take a time for check it. i try to maintain the code the more uniformly possible.

Regards.

### CODE REVIEW

**Comment by t3chnoboy** [comment]
Great job!
Thank you!

**Comment by t3chnoboy** [comment]
Would you mind if I add you to the repo as collaborator?

**Comment by JuanCrg90** [comment]
That would be great :smiley:

**Comment by t3chnoboy** [comment]
Done!

**Comment by JuanCrg90** [comment]
Thank You :smile:

**Pull request merged**
