### PR TITLE
Allow item search with multiple item ids

### PR DESCRIPTION
**Pull request by FrankBowers24**
I have been doing similarity searches which return up to five itemids.  I would like to look up all five ids in one call passing in a comma-separted list of ids.  If the commas are not escaped I get a cryptic error message from Amazon.

### CODE REVIEW

**Comment by t3chnoboy** [comment]
Hi!
Nice addition! Thank you!
However the tests are failing. Could you please take a look at them, I'll only have the chance to do so on the weekend.
We could use ```encodeURIComponent```  function instead of ```replace(/,/g, '%2C');```. What do you think?

**Comment by FrankBowers24** [comment]
Yes, encodeURIComponent would be a better choice.

**Comment by t3chnoboy** [comment]
Can you update the method and push --force to this branch?

**Comment by FrankBowers24** [comment]
Which branch?  develop, master, or streams?  I can do it tonight.

**Comment by t3chnoboy** [comment]
master

**Comment by FrankBowers24** [comment]
I don't have access permission to push to your repo.  I updated the pull request to use encodeURIComponent.

**Comment by t3chnoboy** [comment]
Sorry for the late response, I had finals this week.
I've checked you branch locally and it worked. Looks like something's wrong with the PR checker.
Merging this. Thank you! Great work!

**Pull request merged**
