### PR TITLE
Add query for proxy server

### PR DESCRIPTION
**Pull request by sorensenjg**

### CODE REVIEW

**Comment by sorensenjg** [comment]
I'm not entirely sure.. I am using amazon-product-api in a react app and i have been banging my head against the desk for the last day or two trying to figure out why my get request was getting a CORS error. I discovered that the use of a proxy server was necessary, however there was no way of adding this to the request directly. Do you have an better/alternative way to implement this? If so, please share an example. Thanks!

**Comment by masterT** [comment]
You should use the library on the server side.

**Comment by sorensenjg** [comment]
@masterT Would you mind explaining why it should be used on the server side?

**Comment by masterT** [comment]
It would expose your API secret if you use it from the browser.

**Comment by sorensenjg** [comment]
Got it! I knew i was missing something really obvious.. Thanks

**Pull request closed without merging**
